# When supported, the build process instructs the C compiler
# or the C preprocessor to find the prerequisites of each
# object file (*.o) that is produced; this file was generated
# automatically from the results of that prerequisite search,
# and is meant to be used as a static substitute when such a
# search is not supported.
#
# In order to facilitate the review of alterations to this
# file, its content has been spread across as many lines
# as possible.

circbuffer.o \
: \
$(srcdir)/circbuffer.h \

common-chansession.o \
: \
$(srcdir)/buffer.h \
$(srcdir)/channel.h \
$(srcdir)/chansession.h \
$(srcdir)/circbuffer.h \
$(srcdir)/listener.h \
$(srcdir)/loginrec.h \

dbhelpers.o \
: \
$(srcdir)/dbhelpers.h \

dh_groups.o \
: \
$(srcdir)/config.h \
$(srcdir)/options.h \
$(srcdir)/sysoptions.h \
config-raw.h \
default_options.h \
localoptions.h \

dss.o \
: \
$(srcdir)/dss.h \

list.o \
: \
$(srcdir)/list.h \

loginrec.o \
: \
$(srcdir)/loginrec.h \

dropbearconvert.o \
keyimport.o \
: \
$(srcdir)/keyimport.h \

dropbearkey.o \
svr-kex.o \
: \
$(srcdir)/gensignkey.h \

genrsa.o \
rsa.o \
: \
$(srcdir)/buffer.h \
$(srcdir)/dbhelpers.h \
$(srcdir)/dbutil.h \
$(srcdir)/queue.h \
$(srcdir)/rsa.h \

progressmeter.o \
scp.o \
: \
$(srcdir)/progressmeter.h \

sshpty.o \
svr-chansession.o \
: \
$(srcdir)/sshpty.h \

svr-chansession.o \
svr-x11fwd.o \
: \
$(srcdir)/x11fwd.h \

cli-chansession.o \
svr-chansession.o \
termcodes.o \
: \
$(srcdir)/termcodes.h \

cli-runopts.o \
common-runopts.o \
svr-runopts.o \
: \
$(srcdir)/algo.h \
$(srcdir)/auth.h \
$(srcdir)/buffer.h \
$(srcdir)/channel.h \
$(srcdir)/chansession.h \
$(srcdir)/circbuffer.h \
$(srcdir)/dbhelpers.h \
$(srcdir)/dbutil.h \
$(srcdir)/dss.h \
$(srcdir)/list.h \
$(srcdir)/listener.h \
$(srcdir)/loginrec.h \
$(srcdir)/queue.h \
$(srcdir)/rsa.h \
$(srcdir)/runopts.h \
$(srcdir)/signkey.h \
$(srcdir)/tcpfwd.h \

common-algo.o \
common-kex.o \
dh_groups.o \
: \
$(srcdir)/dh_groups.h \

common-algo.o \
crypto_desc.o \
ltc_prng.o \
: \
$(srcdir)/ltc_prng.h \

dropbearkey.o \
gendss.o \
gensignkey.o \
: \
$(srcdir)/gendss.h \

dropbearkey.o \
genrsa.o \
gensignkey.o \
: \
$(srcdir)/dbrandom.h \
$(srcdir)/genrsa.h \

progressmeter.o \
scp.o \
scpmisc.o \
: \
$(srcdir)/scpmisc.h \

cli-session.o \
packet.o \
process-packet.o \
svr-service.o \
svr-session.o \
: \
$(srcdir)/service.h \

dropbearkey.o \
ecdsa.o \
gensignkey.o \
signkey.o \
svr-runopts.o \
: \
$(srcdir)/ecdsa.h \

cli-agentfwd.o \
cli-authpubkey.o \
cli-chansession.o \
cli-session.o \
svr-agentfwd.o \
svr-chansession.o \
: \
$(srcdir)/agentfwd.h \
$(srcdir)/ssh.h \

atomicio.o \
cli-agentfwd.o \
dbutil.o \
loginrec.o \
progressmeter.o \
scp.o \
svr-session.o \
: \
$(srcdir)/atomicio.h \

dropbearconvert.o \
dropbearkey.o \
ecdsa.o \
gendss.o \
gensignkey.o \
keyimport.o \
signkey.o \
: \
$(srcdir)/buffer.h \
$(srcdir)/dbhelpers.h \
$(srcdir)/dbutil.h \
$(srcdir)/dss.h \
$(srcdir)/queue.h \
$(srcdir)/rsa.h \
$(srcdir)/signkey.h \

cli-kex.o \
common-algo.o \
common-kex.o \
crypto_desc.o \
ecc.o \
ecdsa.o \
keyimport.o \
svr-kex.o \
: \
$(srcdir)/ecc.h \

cli-main.o \
cli-session.o \
common-kex.o \
crypto_desc.o \
dropbearconvert.o \
dropbearkey.o \
ecdsa.o \
svr-main.o \
svr-session.o \
: \
$(srcdir)/crypto_desc.h \

cli-kex.o \
common-kex.o \
dbrandom.o \
dss.o \
ecc.o \
gendss.o \
genrsa.o \
keyimport.o \
rsa.o \
svr-kex.o \
: \
$(srcdir)/bignum.h \

bignum.o \
buffer.o \
circbuffer.o \
crypto_desc.o \
dbrandom.o \
dss.o \
ecc.o \
list.o \
loginrec.o \
queue.o \
sshpty.o \
: \
$(srcdir)/buffer.h \
$(srcdir)/dbhelpers.h \
$(srcdir)/dbutil.h \
$(srcdir)/queue.h \

cli-agentfwd.o \
cli-auth.o \
cli-authinteract.o \
cli-authpasswd.o \
cli-authpubkey.o \
cli-chansession.o \
cli-kex.o \
cli-main.o \
cli-session.o \
cli-tcpfwd.o \
common-channel.o \
common-kex.o \
common-session.o \
svr-auth.o \
svr-authpasswd.o \
svr-chansession.o \
svr-kex.o \
svr-main.o \
svr-session.o \
svr-tcpfwd.o \
tcp-accept.o \
: \
$(srcdir)/runopts.h \

cli-agentfwd.o \
cli-kex.o \
cli-main.o \
cli-session.o \
common-kex.o \
common-runopts.o \
common-session.o \
dbrandom.o \
dropbearconvert.o \
dss.o \
gendss.o \
ltc_prng.o \
packet.o \
process-packet.o \
rsa.o \
svr-agentfwd.o \
svr-auth.o \
svr-chansession.o \
svr-kex.o \
svr-main.o \
svr-session.o \
: \
$(srcdir)/dbrandom.h \

cli-auth.o \
cli-authinteract.o \
cli-authpasswd.o \
cli-channel.o \
cli-kex.o \
cli-tcpfwd.o \
common-channel.o \
common-kex.o \
common-session.o \
dss.o \
packet.o \
process-packet.o \
rsa.o \
signkey.o \
svr-auth.o \
svr-authpubkey.o \
svr-kex.o \
svr-service.o \
svr-session.o \
svr-tcpfwd.o \
svr-x11fwd.o \
tcp-accept.o \
: \
$(srcdir)/ssh.h \

cli-agentfwd.o \
cli-auth.o \
cli-authinteract.o \
cli-authpasswd.o \
cli-authpubkey.o \
cli-channel.o \
cli-chansession.o \
cli-kex.o \
cli-main.o \
cli-session.o \
cli-tcpfwd.o \
common-algo.o \
common-channel.o \
common-kex.o \
common-session.o \
dbutil.o \
listener.o \
netio.o \
packet.o \
process-packet.o \
svr-agentfwd.o \
svr-auth.o \
svr-authpam.o \
svr-authpasswd.o \
svr-authpubkey.o \
svr-authpubkeyoptions.o \
svr-chansession.o \
svr-kex.o \
svr-main.o \
svr-service.o \
svr-session.o \
svr-tcpfwd.o \
svr-x11fwd.o \
tcp-accept.o \
: \
$(srcdir)/algo.h \
$(srcdir)/auth.h \
$(srcdir)/buffer.h \
$(srcdir)/channel.h \
$(srcdir)/chansession.h \
$(srcdir)/circbuffer.h \
$(srcdir)/dbhelpers.h \
$(srcdir)/dbutil.h \
$(srcdir)/dss.h \
$(srcdir)/kex.h \
$(srcdir)/list.h \
$(srcdir)/listener.h \
$(srcdir)/loginrec.h \
$(srcdir)/netio.h \
$(srcdir)/packet.h \
$(srcdir)/queue.h \
$(srcdir)/rsa.h \
$(srcdir)/session.h \
$(srcdir)/signkey.h \
$(srcdir)/tcpfwd.h \

atomicio.o \
bignum.o \
buffer.o \
circbuffer.o \
cli-agentfwd.o \
cli-auth.o \
cli-authinteract.o \
cli-authpasswd.o \
cli-authpubkey.o \
cli-channel.o \
cli-chansession.o \
cli-kex.o \
cli-main.o \
cli-runopts.o \
cli-session.o \
cli-tcpfwd.o \
common-algo.o \
common-channel.o \
common-chansession.o \
common-kex.o \
common-runopts.o \
common-session.o \
compat.o \
crypto_desc.o \
dbhelpers.o \
dbmulti.o \
dbrandom.o \
dbutil.o \
dropbearconvert.o \
dropbearkey.o \
dss.o \
ecc.o \
ecdsa.o \
fake-rfc2553.o \
gendss.o \
genrsa.o \
gensignkey.o \
keyimport.o \
list.o \
listener.o \
loginrec.o \
ltc_prng.o \
netio.o \
packet.o \
process-packet.o \
progressmeter.o \
queue.o \
rsa.o \
scp.o \
scpmisc.o \
signkey.o \
sshpty.o \
svr-agentfwd.o \
svr-auth.o \
svr-authpam.o \
svr-authpasswd.o \
svr-authpubkey.o \
svr-authpubkeyoptions.o \
svr-chansession.o \
svr-kex.o \
svr-main.o \
svr-runopts.o \
svr-service.o \
svr-session.o \
svr-tcpfwd.o \
svr-x11fwd.o \
tcp-accept.o \
termcodes.o \
: \
$(srcdir)/compat.h \
$(srcdir)/config.h \
$(srcdir)/debug.h \
$(srcdir)/fake-rfc2553.h \
$(srcdir)/includes.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_argchk.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_cfg.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_cipher.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_custom.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_hash.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_mac.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_macros.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_math.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_misc.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_pk.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_pkcs.h \
$(srcdir)/libtomcrypt/src/headers/tomcrypt_prng.h \
$(srcdir)/libtommath/tommath.h \
$(srcdir)/libtommath/tommath_class.h \
$(srcdir)/libtommath/tommath_superclass.h \
$(srcdir)/options.h \
$(srcdir)/sysoptions.h \
config-raw.h \
default_options.h \
localoptions.h \
